web/default/pilight.js
Added French translations for pilight web interface
=> Added French translations

libs/operators/div.c, libs/operators/div.h, libs/operators/mod.c, libs/operators/mod.h
Hello CurlyMo,
Sorry for the delay, I was ill.
This pull request you asked for is my first real one, please let me know if this is OK.
If so, I will make a pull request for the MOD operator too.
Grts,
Niek
=> DIV operator v1.0

libs/protocols/alecto_ws1700.c, libs/protocols/alecto_wsd17.c, libs/protocols/alecto_wx500.c, libs/protocols/auriol.c, libs/protocols/ninjablocks_weather.c, libs/protocols/teknihall.c
Initialize offset variables in dynamically allocated memory structure.
=> Initialize variables with offset values after allocation of structure

libs/pilight/events/actions/sendmail.c, libs/pilight/events/actions/sendmail.h
Added validity check for mail address
Adapted to new library structure
Assigned action arguments to mail struct directly
Several fixes
=> updated sendmail action

libs/pilight/config/settings.c
added smtp settings with EVENTS define
improved regex for e-mail addresses
=> updates settings.c

libs/pilight/hardware/433nano.c
Depends on similar PR for pilight-usb-nano
=> Broken sending via pilight-usb-nano

receive.c
This filters the pilight-receive output and removes the JSON objects for the datetime protocol. Invoke pilight-receive with pilight-receive -F to use.
=> Add pilight-receive datetime filtering.

libs/pilight/protocols/433.92/rsl366.c
Fixed RSL366T remote code parsing
Reduced the number of false positives for arctech_switch_old based on the description (https://wiki.pilight.org/doku.php/arctech_switch_old) which says bit[11]=0
=> Fix RSL366T remote code parsing

libs/pilight/events/actions/dim.c, libs/pilight/events/actions/label.c, libs/pilight/events/actions/switch.c
This fixed the segmentation fault described in [this thread] (http://forum.pilight.org/Thread-Bug-report-segmentation-fault-using-rule-with-AFTER)
=> Moved array_free after logprintf

libs/pilight/core/binary.c, libs/pilight/core/binary.h
* Fix int-to-binary conversion for zero value (no "bits" were generated)
* Fix int-to-binary conversion for negative values (busy loop).
* Improve int-to-binary conversions and vice/versa.
=> * Fix and improve int-to-binary conversion

libs/pilight/protocols/433.92/tfa.c
Change is compatible with standard tfa and conrad weather device
https://forum.pilight.org/Thread-Protocols-with-Header-and-Footer?pid=17260#pid17260
=> Fix header footer issue for Dostman 30.3200 device.

libs/pilight/protocols/433.92/tfa.c
https://forum.pilight.org/Thread-Soens-Innovation-TFA-similar-protocol?pid=17605#pid17605
=> Support for SOENS Wheatherstation added to tfa protocol

libs/pilight/protocols/433.92/quigg_gt9000.c
Hi,
this PR adds further GT-9000 protocol support - more systemcodes are supported now.
Regards,
Dominik
=> add further GT-9000 support

libs/pilight/protocols/433.92/quigg_gt9000.c
- support further syscodetype (1, 7)
- removed duplicate code for hashes
- change on/off state calculation code
=> further GT-9000 protocol support

daemon.c, libs/pilight/protocols/433.92/somfy_rts.c, libs/pilight/protocols/protocol.c, libs/pilight/protocols/protocol.h, libs/webgui/pilight.css, libs/webgui/pilight.js
Bug fixes in .c and .h modules.
pilight.js:
A 3rd Button for screen devices was added:
- The 3rd button is only visible on the GUI for screen devices using the protocol somfy_rts, all other protocols will show 2 buttons
- The field length for the screen devices was adjusted in order to provide sufficient space for all supported languanges.
=> Updated s*mfy protocol stack

libs/pilight/events/operators/isnot.c, libs/pilight/events/operators/isnot.h
This operator takes two string operands (just like the IS operator) and
evaluates to TRUE if the operands are NOT equal.
=> Created ISNOT operator

libs/pilight/protocols/433.92/auriol.c
`MIN_PULSE_LENGTH`  must be smaller than `MAX_PULSE_LENGTH` to work.
Use id instead of channel as `id` and publish the channel as `channel`.
=> auriol weather station protocol fix

libs/pilight/protocols/433.92/CMakeExclude.txt, libs/pilight/protocols/433.92/ev1527.c, libs/pilight/protocols/433.92/mumbi.c
I found some typos, just by chance.
=> fix some typos

libs/pilight/config/devices.c
https://forum.pilight.org/Thread-Oregon-THGR122NX?pid=18378#pid18378
=> Update json elements with conftype DEVICES_OPTIONAL

libs/pilight/protocols/433.92/alecto_ws1700.c
https://forum.pilight.org/Thread-Fully-Supported-No-brand-temp-humidity-sensor-alecto-ws1700?pid=17700#pid17700
This is my first pull-request! So please check and double-check ;-)
=> Corrections in protocol, header/id and temperature

libs/pilight/protocols/433.92/quigg_gt1000.c
I have some Lidl switches and got them working by adding the random codes to the protocol. As I am a developer but have not used GitHub before I wanted to push my changes myself. So this is my first pull request! Hope I followed the manual correctly and checked all the correct tickboxes :-)
=> Added random codes for group id 0 (Lidl switches)

libs/pilight/protocols/433.92/arctech_screen_old.c
https://forum.pilight.org/Thread-pilight-7-and-Intertechno-CMR-500?pid=19512#pid19512
=> Bugfixing arctech_screen_old protocol

flash.c, libs/pilight/core/config.c, libs/pilight/protocols/API/cpu_temp.c, libs/pilight/protocols/GPIO/ds18b20.c, libs/pilight/protocols/GPIO/ds18s20.c
Based this on the development branch
=> Replace 'does not exists' with 'does not exist'

libs/pilight/protocols/433.92/elro_800_switch.c
Some switches, like the Maxi-Tronic swtich (see pull request #278), using additional Med states (long-short-long-short pulse) in the systemcode. This commit support this kind of switches by supporting systemcodes > 31.
=> elro_800_switch: support of Med-states in systemcode

libs/pilight/core/binary.c, libs/pilight/core/binary.h, libs/pilight/protocols/433.92/alecto_ws1700.c, libs/pilight/protocols/433.92/alecto_wx500.c, libs/pilight/protocols/433.92/auriol.c, libs/pilight/protocols/433.92/tcm.c, libs/pilight/protocols/433.92/tfa.c
As discussed in #309, here are two functions to convert a binary array to signed integer.
In addition I used this function in some protocols, were the logic is the same.
I tested with tcm and auriol in the range of -10°C to +20°C.
If required, I will squash the commits.
=> Introduce function to convert from binary to signed

res/init/pilight.initd
https://forum.pilight.org/Thread-Raspbian-jessie-pilight-7-no-pilight-ssdp-connections-found?pid=20307#pid20307
=> Do not start pilight without network

libs/wiringx/raspberrypi.c
Replaces PR #324 
https://forum.pilight.org/Thread-Boot-from-USB?pid=20427#pid20427
=> Kernel 4.9.x compatibility update wiringx

libs/pilight/core/mail.c
Terminate sendmail actions whenever Error 4xx and 5xx are reported back.
=> Improved status checking in mail.c in accordance to RFC requirements

libs/pilight/core/webserver.c, libs/pilight/protocols/protocol.c, tests/CMakeLists.txt, tests/protocols_433.c
Also fixes build error when WEBSERVER_HTTPS is not defined.
=> Not all fields of protocol_t were initialized in protocol_register()

clients/process.py3
Use PEP8 code style:
* Use consistent indentation
* Remove unused imports
* Remove unused argument timeout of `discover()`
* Add spaces after "`,`"
* Remove "`;`" at end of lines
* Break up long lines (max 80 characters)
* Remove redefined variables from outer scopes
* Change blind except to properly except the `IOError ("[Errno 11] Resource
temporarily unavailable")` whereupon no ssdp connections are found
* Update copyright year
* Add module and function docstrings
The `pylint` tool is happy with the style (10.00/10.00)
Add Python 3 version of example client
**Implements retries** and some basic error handling.
Retries are a given as a kwarg to discover(). In case one response does not
actually work, the code will move on to the next SSDP response, until it can
connect or runs out of …
=> Update and improve Python example clients

clients/process.py3
Use PEP8 code style:
* Use consistent indentation
* Remove unused imports
* Remove unused argument timeout of discover()
* Add spaces after ,
* Remove ; at end of lines
* Break up long lines (max 80 characters)
* Remove redefined variables from outer scopes
* Change blind except to properly except the IOError ("[Errno 11] Resource
temporarily unavailable") whereupon no ssdp connections are found
* Update copyright year
* Add module and function docstrings
The pylint tool is happy with the style (10.00/10.00)
Add Python 3 version of example client
Implements retries and some basic error handling.
Retries are a given as a kwarg to discover(). In case one response does not
actually work, the code will move on to the next SSDP response, until it can
connect or runs out of responses.
Backport …
=> Example clients: Add Python 3 example, fix style, add retries

clients/process.py, clients/process.py3
Also fix indentation and uncomment a print in the python2 version
=> Python clients: Change license to MPLv2 [rewrite]

daemon.c
Don't change the log level when using --nodaemon. Add --verbose option to set the log level to debug.
This is for better integration with systemd to be able to prevent pilight from forking without increasing the log level.
=> Split --nodaemon option into --nodaemon and --verbose

receive.c
Also removes tabs at the end of some lines
I'm thinking about adding a second type of filtering, allowing users to filter **for** a specific protocol(s). This is useful with weather sensors, when the ID has changed after changing the batteries, so that users don't have to list every protocol that isn't wanted in the output of pilight-receive, but rather specify which one(s) they _want_ to see.
i think I would do it like this:
* Repurpose the `-F` flag to become a "real" filter, i.e. it only outputs the specified protocols (`-F alecto_wsd17` would only output `alecto_wsd17` signals). Listing several protocols should be supported I think - it doesn't add a lot of bloat but it might be useful in certain situations.
* Add a `-X` (`--eXclude`) flag to list protocols that should be excluded …
=> Port pilight-receive filtering feature to rewrite

docs/source/protocols/433.92/weather/tcm.rst
As requested in #277, the documentation of the TCM protocol.
Comments are welcome.
=> [Docs] TCM 218943 weather station protocol

ci/travis-after-success.sh
This should fix gcov not being able to find its files
=> Fix coveralls in travis builds

libs/pilight/core/binary.c, libs/pilight/core/binary.h, tests/binary.c
This is a port of #314 to the rewrite branch with the aim to integrate unit tests for this functions.
=> unit tests for binToSigned() and binToSignedRev()

docs/source/installation.rst
This adds some missing information and a missing library for the self compiling part. Also I removed the dependent libraries from the list since they made it harder to read.
=> make self compiling more precise

libs/pilight/config/devices.c
In devices.c a fixed size buffer was being used to hold device strings. If a device string was too long to fit in the buffer a segfault could occur.
The buffer for device strings has now been changed from fixed- to dynamic size.
The buffer is initialized with 255 bytes like before, but more space is now allocated in case this is not sufficient.
=> fixed segfault occuring with long device strings
