pilight/pilight

libs/pilight/protocols/API/wunderground.c
Hey guys,
i am living in Mülheim an der Ruhr (Germany) and had some troubles to get the wunderground working  because my location is "mulheim_an_der_ruhr" at wunderground api. So i fixed the regex to support "_" in the location field.
=> Supporting "_" in location of wunderground api

libs/pilight/protocols/433.92/x10.c
This bug caused sending of the same raw codes for unit codes with a numeric part of 8 and 9.
=> fixed bug in x.10 protocol

libs/pilight/events/functions/date_format.c
Call of mktime() for setting all fields in struct tm for date_format
=> uninitialised fields of tm

libs/pilight/protocols/433.92/conrad_rsl_switch.c
Add option -l for learn mode to increase send repeat from 10 to 40. Tested with Conrad RSLU Switch.
=> Add learn mode to conrad_rsl_switch protocol

libs/pilight/protocols/433.92/arctech_dusk.c
"dusk" and "dawn" states were mixed up
=> Swapped arctech_dusk states

libs/pilight/protocols/433.92/quigg_gt7000.c
Support setting 0 as an "id" value for the quigg_gt7000 protocol, it is required for some switches.
=> Quigg_gt7000: Allow 0 for ID

CMakeConfig.txt, libs/pilight/protocols/433.92/quigg_gt9000.c, libs/pilight/protocols/433.92/quigg_gt9000.h
This pull request contains basic GT-9000 (GT-FSI-06 switch) support. GT-9000 protocol seems to be encrypted and currently I couldn't find any details about the encryption.
Protocol supports sending and receiving
- systemcode (bits 0-3)
- payload (bits 4-15)
- ON/OFF combinations (bits 16-19)
- unit (bits 20-23)
- footer (bit 24)
State is not supported yet, as the state seems to be encoded in the payload part. GT-9000 remotes sends 4 different payloads for each button.
It's possible to use one of the 4 payloads to program the switch and use the other 3 to control the switch as well. It would also be possible to do button detection based on the 4 payloads in fhem or others.
I hope that this basic implementation helps others and maybe somebody has an idea to decode the payload as well.
=> Add support for GT-9000 protocol

libs/pilight/protocols/433.92/tfa30.c
The id variable was not defined when necessary, fixed by defining the id variable. Patch by DonBernos.
Discussion: https://forum.pilight.org/Thread-TFA-30-3125-Temp-Hum-TFA-31-3120-90-Temp?page=7
=> tfa30 protocol: Fix temperature and humidity offsets not working.

libs/pilight/protocols/433.92/ev1527.c
The escape sequence \d is not known to all compilers. Thus I replaced it with [0-9].
=> Fix compiler warning: unknown escape sequence: '\d'

libs/pilight/core/json.c
If out-of-memory happend in json_strdup() the application crashed due to a
segmentation fault rather then terminate regularly. This has been fixed.
=> Fix potential NULL pointer access in json_strdup().

daemon.c, debug.c
Fix memset-length parameter when initializing buffers that are arrays of
elements larger than byte (multiply the length by sizeof(buffer[0])
or just use sizeof(buffer)).
=> Fix incomplete buffer initialization.

libs/pilight/protocols/433.92/clarus.c
pilight_send will crash if called with a very (e.g. 80 chars) long --id. In this case an on-stack buffer
overflow happens. This has been fixed.
=> Fix pilight-send crash on clarus_switch protocol if called with

libs/pilight/core/common.c
A buffer allocated by setenv() and unsetenv() was one byte too short.
If setenv() was called with option to not overwrite an existing variable
and that variable does not exist, then a NULL pointer was used and a
segfault happens (if the variable exists, it was unnecessary set again
to its current value). All this has been fixed.
Further the parameters passed to setenv() and unsetenv() are now checked
against NULL pointers and the functions do the best they can do without
crashing (return with failure indicator and errno set). This introduced
a feature for setenv() that, if called with a variable name but a value
of NULL, it does an unsetenv().
=> Fix buffer overflow in setenv() and unsetenv() functions.

libs/pilight/protocols/433.92/alecto_wx500.c
This fix works by reading a signed bit from the code, indicating whether the temperature should be positive or negative. Original fix by Tommybear1979.
=> alecto_wx500: Fix negative temperatures

res/init/pilight.initd
This fixes "Service does not start correctly when booting" on Raspberry PI 2
https://forum.pilight.org/Thread-Service-does-not-start-correctly-when-booting
=> Requiring network before starting the service.

libs/pilight/protocols/433.92/alecto_wx500.c
There is a bug in the alecto_wx500 protocol I found by an analysis by valgrind.
RAWLENGTH is 74 and thus the binary array has a length of 37 but because of "rawlen-1" in the for loop bit 36 of the binary array is not set.
Because of this valgrind gives an "Conditional jump..." error in line 81 when this bit is used.
With this fix there were no valgrind errors for this protocol any more.
=> fix alecto_wx500 protocol

libs/pilight/protocols/433.92/rsl366.c
There is a bug in the rsl366 protocol I found by an analysis by valgrind.
RAWLENGTH is 50 and thus rawlen-1 should be 49.
Thereby the for loop increments x until 48.
But then raw[x+3] will read beyond the raw array.
However, valgrind did not log invalid writes in line 70 or 72 which I cannot explain.
Perhaps someone with rsl366 hardware can test this fix.
I have no rsl366 hardware and, when I made the test, the event seemed to be triggered by RF noise.
With this fix there were no valgrind errors any more for this protocol.
=> fix read beyond raw array in rsl366 protocol

libs/pilight/protocols/433.92/elro_300_switch.c
Because the rawlen array has twice the size of the binary array there is currently a buffer overflow which can make pilight crash. This happened for my but the event was triggered by RF noise. Unfortunately I have no device using the elro_300_switch protocol so that I could test the changed code. But with this code there are no longer crashes.
=> fix buffer overflow in elro_300_switch protocol

libs/pilight/protocols/433.92/tfa.c
I'm using several tempeature / humidity sensors using the tfa protocol and had regulary completely wrong values in the logs due to broken RF telegrams.
Thus I analyzed the RF telegrams and could find out that the last 4 bits are a CRC-4 checksum.
I have added a checksum verification to the code and now I have no longer problems with wrong values due to broken RF telegrams.
=> verify checksum for tfa protocol

libs/pilight/protocols/433.92/arctech_switch_old.c
I'm using remotes with the arctech_switch_old protocol and had often the problem that for example if I pushed an on button some of the telegrams send by the remote were recognized as off or even another id was recognized.
From the code it's clear that the telegrams can be divided in 4 bit parts which are either 1001 or 0110. When I analyzed the telegrams send by the remotes I noticed that the telegrams for which a wrong state or id was recognized did not match this scheme completely but the current parseCode function does only evaluate every fourth bit to distignuish between 1001 and 0110.
Thus by my pull request now all bits are evaluated and, if a 4 bit block does not match 1001 or 0110, the telegram is discarded.
With this change I no longer have the problem of wrongly recongized …
=> telegram check added for arctech_switch_old protocol

libs/pilight/protocols/433.92/tfa.c
- Freetech NC-7104-675 (Soens with longer footer - 9050 range)
https://forum.pilight.org/Thread-Freetec-Temp-Humidity-Sensor?pid=16105#pid16105
- Globaltronics GT-WT-01 (Soens with longer footer 9050 range)
https://forum.pilight.org/Thread-Weather-Station-Globaltronics-GT-WT-01?pid=16234#pid16234
- Compatibility with 433USBnano (increase footer to 9300 range as reported in the forum link below)
https://forum.pilight.org/Thread-Freetec-Temp-Humidity-Sensor?pid=16105#pid16105
Pulse duration for binary decoding routine set back to original tfa protocol (bug fixing)
=> Support Freetech NC-7104-675, Globaltronics GT-WT-01

libs/pilight/protocols/GPIO/ds18b20.c
The value was assigned to a wrong and not yet allocated structure
=> Fix segmentation fault code in ds18b20 driver

libs/pilight/protocols/433.92/eurodomest_switch.c
Was 0...3, but is corrected to 1...4
Tested and working
=> Corrected unit range of Eurodomest switch protocol

libs/pilight/config/settings.c, libs/pilight/core/common.c, libs/pilight/core/common.h, libs/pilight/events/actions/sendmail.c
Previous check of e-email addresses was too strict.
This has been fixed, they are now checked more precise.
Implemented a common function check_email_addr() that can optionally
also accept lists of e-mail addresses. The option to check e-mail
domain names against DNS is prepared but ignored in the moment.
=> Fix checking e-mail addresses; Added a common function to check them.

libs/pilight/protocols/433.92/quigg_gt9000.c
Some sockets had problems with 300. 500 should work for all of them.
=> GT9000: Change short pulse to 500

libs/pilight/core/log.c
These occurred for example when accessing an invalid page on the webserver (x.x.x.x:5000/conf for example)
Before:
```
[Jun 13 12:55:22:359922] WARNING:[Jun 13 12:55:22:567092] DEBUG: new client, ip: 127.0.0.1, port: 51047
```
After:
```
[Jun 13 13:19:55:969887] WARNING: (webserver) could not read /usr/local/share/pilight//conf
```
=> Fix blank warning log messages

daemon.c, flash.c, libs/pilight/core/arp.c, libs/pilight/core/datetime.c, libs/pilight/core/firmware.c, libs/pilight/core/http.c, libs/pilight/core/log.c, libs/pilight/core/mail.c, libs/pilight/core/options.c, libs/pilight/core/sha256cache.c, libs/pilight/core/socket.c, libs/pilight/core/ssdp.c, libs/pilight/core/webserver.c, libs/pilight/events/actions/dim.c, libs/pilight/events/actions/label.c, libs/pilight/events/actions/sendmail.c, libs/pilight/events/actions/switch.c, libs/pilight/events/actions/toggle.c, libs/pilight/events/events.c, libs/pilight/hardware/zwave.cpp, libs/pilight/storage/storage.c, send.c
Fix several minor spelling/copy-paste errors.
arp.c: clarify error message
datetime.c: fix spelling
firmware.c: fix spelling
http.c: fix error messages
log.c: fix spelling
mail.c: fix error messages
options.c: fix spelling
sha256chache.c: fix spelling
socket.c: fix log message and spelling
ssdp.c: fix log message
webserver.c: fix spelling in log messages and REST error messages
events.c: fix spelling
dim.c: fix spelling, remove contractions, fix copy-paste errors
label.c: fix spelling, remove contractions, fix copy-paste errors
sendmail.c: fix spelling
switch.c: fix spelling, remove contractions, fix copy-paste errors
toggle.c: fix spelling, remove contractions
zwave.cpp: fix spelling
storage.c: fix spelling
daemon.c: fix spelling in log messages
flash.c: fix spelling
send.c: remove …
=> Various minor spelling fixes

CMakeLists.txt
Libraries for AArch64 built distributions, like for the PINE64, can be found in /usr/lib/aarch64-linux-gnu.
=> Add support for AArch64 to CMakeLists.txt

libs/pilight/protocols/433.92/tcm.c
The temperature is a signed integer, so we have to handle the negative case.
=> TCM 218943 weather station: support negative temperature

libs/pilight/protocols/generic/generic_dimmer.c, libs/webgui/pilight.js
Fix 2 dimmer bugs
These are two separate commits since they are quite different, yet I feel that they are too similar to warrant opening separate PRs. Hope that's fine.
Discussion: https://forum.pilight.org/Thread-Dimlevel-text-in-WebGUI-0-and-not-updated
Commit messages: 
----
Webgui: Fix dimmer display bugs
This would cause the text field next to the slider to be
initialized to 0 at page load, even though the slider was showing the
correct dimlevel.
This commit fixes this by also assigning the dimlevel to the text field on
page load. Patch by @Niek.
Further, the slider-input field was editable, but without use (editing the
value has no effect). Therefore, display the field as disabled.
----
generic_dimmer: Fix inconsistency
The default max values were defined to different values in the …
=> Dimmer patches

daemon.c
Send a json object immediately after replying to a `{"request values"}` socket
API message was received. Up to GUIs and other software using the API to parse
this.
The version packet looks like: `{"version":"7.0"}`
This is documented in the documentation already, but it wasn't actually present in the code. But it's very useful for programs using the API, since it is better than reading values from the registry that could easily be modified.
=> daemon: Add version packet sent after {"request values"}

libs/pilight/protocols/433.92/teknihall.c
The values were distorted, fixed by checking for unreasonably high value and subtracting 102.4°.
Discussion: https://forum.pilight.org/Thread-negative-Temperature-for?pid=16687#pid16687
=> Teknihall: Fix negative temperatures

libs/pilight/protocols/433.92/teknihall.c
Fixes mistake in 2f97e6a52b2c8fcdecaeff8e8748728446121e40
Sorry about that :/
=> Teknihall: Use correct bits in signed temperature

libs/pilight/core/json.h
The former json types could not easily be used as bitmask, because the
values had some bits in common. For example JSON_STRING (0x04) and
JSON_ARRAY (0x16) had both the third bit set to true. So a calue
defined as JSON_ARRAY had internally the same value as
(JSON_STRING | JSON_ARRAY).
This is a problem, since for example teh generic_label protocol uses
bitwise or to declare a parameter as "multiple types" (in this case its
JSON_STRING | JSON_NUMBER.
This uses bitshifts to define differentiable values.
Signed-off-by: Jan Losinski <losinski@wh2.tu-dresden.de>
=> Make json type defines useable as bitmask

CMakeConfig.txt, libs/pilight/protocols/433.92/CMakeExclude.txt, libs/pilight/protocols/433.92/livolo_switch.c, libs/pilight/protocols/433.92/livolo_switch.h
Here's an implementation of the protocol used by Livolo wireless switches (and their clones).
Protocol description was taken from here: http://platenspeler.github.io/DeveloperGuide/433Transmitters/433messaging.html
Remote keycodes were taken from here: https://github.com/platenspeler/LamPI-2.0/tree/master/transmitters/livolo
Unfortunately, it's impossible to implement reading of the protocol with current pilight architecture, because livolo protocol doesn't have footer (which is used by pilight to extract a pulsetrain). It means that only send functionality is supported ATM. I'm open to suggestions on how to implement parsing of the protocol.
The protocol was tested with several switches that I have at home and works well with all of them.
=> Livolo protocol (send only)

clients/process.py, clients/process.py3
Also fix indentation and uncomment a print in the python2 version
=> Python clients: Change license to MPLv2

libs/pilight/protocols/GPIO/bmp180.c, libs/pilight/protocols/GPIO/lm75.c, libs/pilight/protocols/GPIO/lm76.c
Hi,
has anyone tested the i2c devices (bmp180,lm75,lm76) after the wiringx update ? It dont works because the new i2c-path config-entry-code has a typo..... see attached patch...
Greetz
Marc 
PS: this typo is in the rewrite code also...
=> repair broken i2c devices / new i2c-path config entry

libs/pilight/core/ntp.c
1. Check for failing socket send- and receive was wrong. If receive failed, the result was processed anyway, causing "random" diff values and, as a result, weird datetime values. Fixed by changing the check for the return values.
2. Check for msg.refid was wrong, because refid can have a negative value. In such cases, the result of the ntp request was treated as invalid, causing the "could not sync with ntp server..." message. Fixed by changing the check for the msg.refid value.
=> Fixed ntp bugs

tests/event_actions_mail.c
Joining no threads causes a segfault, fixed my removing thread joining
Segfault:
```
(gdb) run
Starting program: /home/linoM6400/git/pilight/rewrite/build/pilight-unittest 
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.22-4.9.1.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[ test_event_actions_mail_check_parameters         ]
[ test_event_actions_mail_run                      ]
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6c65901 in pthread_join () from /lib64/libpthread.so.0
Missing separate debuginfos, use: zypper install libdbus-1-3-debuginfo-1.8.22-3.1.x86_64 libnl3-200-debuginfo-3.2.23-4.5.x86_64 libpcap1-debuginfo-1.8.1-7.3.1.x86_64 libunwind-debuginfo-1.1-12.5.x86_64
(gdb) bt …
```
=> Fix segfault in event_actions_mail unittests

.travis.yml, ci/travis-after-success.sh, ci/travis-before-install.sh, ci/travis-script.sh
This gives a cleaner `.travis.yml`, making it easier to add more configurations such as other compilers and linting.
=> Restructure travis to ease addition of more configurations

docs/source/protocols/433.92/alarm/secudo.rst
I added a manual page for the secudo protocol and created a pull request.
I created it by using another manual page as template and changing things to the best of my knowledge.
However, I'm not sure about the config stuff contained in the manual page.
The smoke sensors simply send repeatedly a signal if they detect smoke or the test button is pressed which will generate repeatedly corresponding messages in pilight's JSON output with the code changes of commit 91ffcb3.
I personally do not use pilight's gui and have not defined anything for the smoke sensors in the pilight configuration because I only use pilight's JSON output.
I don't know if there is any reasonable output in the gui if one defines such a smoke sensor in pilight's configuration.
=> Added manual page for secudo protocol

libs/webgui/pilight.css
This is a small css modification to allow long captions of switches to break into multiple lines.
=> Break long switch caption in multiple lines

res/init/pilight.initd
https://forum.pilight.org/Thread-Raspbian-jessie-pilight-7-no-pilight-ssdp-connections-found?pid=20422#pid20422
If you get an insserv warning, you may have to remove manually the following link from /etc/rc2.d:
lrwxrwxrwx  1 root root   17 Feb 27  2016 S02pilight -> ../init.d/pilight
=> Bugfix - Update init.d script: Remove pilight stop for runlevel 2

libs/webgui/pilight.css
This fixes the issue with dimmer controls being not high enough reported here:
https://github.com/pilight/pilight/commit/892289638dfa4edb6934e4c05a6bcb3ca16ad3ec#commitcomment-25587958
=> Fix issue with too small dimmer controls

libs/webgui/pilight.css
Currently a label text, longer than 50% of the available width, is only partially visible.
With this commit a label text is allowed to use 95% of the available width and wrap around if it is even longer. 
This ensures that label text is always completely  visible, also on narrow screens.
=> Break up long label text into multiple lines

libs/pilight/core/binary.c, tests/binary.c
Alternative pr for #408 against rewrite branch and with unit tests.
The patch differs from #408 to make `BITS_MSB_FIRST_TO_VALUE()` compatible with unsigned `e`, as in `binToDecRevUl()`.
If some or all commits should be merge, please ask for it.
=> fix handling of s=0 in BITS_MSB_FIRST_TO_VALUE() for rewrite

libs/pilight/core/binary.c
This fix a bug introduced with 5eb10328acfd740570d00825c33f656b9591cc86.
`s` can be 0  as by the coment of `binToDecRev()`: [`0<=s<=e`](https://github.com/pilight/pilight/blob/development/libs/pilight/core/binary.c#L54)
This affect the quigg_gt9000 protocol, as it calls [`binToDecRev()` with `s=0`](https://github.com/pilight/pilight/blob/development/libs/pilight/protocols/433.92/quigg_gt9000.c#L161)
Results of `binToDecRev(binToDecRev((int[]){1,1,1,1, 1,1,1,1}, 0, 7))`:
before 5eb10328acfd740570d00825c33f656b9591cc86: 255
after 5eb10328acfd740570d00825c33f656b9591cc86: 127
this patch: 255
=> binary.c: fix handling of s=0 in BITS_MSB_FIRST_TO_VALUE()

libs/pilight/core/common.c, libs/pilight/psutil/freebsd.c, libs/pilight/psutil/linux.c, libs/pilight/psutil/psutil.h, libs/pilight/psutil/windows.c
Running the slack desktop app while running the unittests revealed that the
process name was too long for the function to store in a char array of size
255. Fixed by increasing the size of the array to 1023, which seems to work
so far.
=> Fix segfault in isrunning() on encountering long process name

CONTRIBUTING.md
The https://www.pilight.org/development/ is dead. I hope https://manual.pilight.org/development/ is the right alternative.
=> Updated development link

libs/pilight/protocols/433.92/alecto_wx500.c
In line 88 the end value of binToDec should be 35 an not 36.
Comparing the other lines you can see that each number consists of 4 bits (nibble)
When you correct the value to 35 the checksum matches and the protocol works for me.
=> Fixed number of readed bits in alecto_wx500.c

libs/pilight/core/common.c, tests/common.c
Added two tests demonstrating a bug in str_replace, causing a wrong new length.
This occurs if:
- The replacement string is longer than the search string and
- The offset of the search string found in the target string is lower than the length of the replacement string minus the length of the search string.
=> Additional unittest for str_replace
